# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'Firebase/Storage'
  pod 'GooglePlaces', '4.2.0'
  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          end
      end
  end

  # Pods for FinalProject

end
